CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_PHY_2M=n

# Bluetooth Host
CONFIG_BT=y
CONFIG_BT_HCI=y
CONFIG_BT_LL_SW_SPLIT=n

# Bluetooth サブシステムのログを詳細化
CONFIG_LOG=y
CONFIG_BT_LOG_LEVEL_DBG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y