manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: akira2390
      url-base: https://github.com/akira2390
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: akira2390
      import: app/west.yml
      revision: core/move-to-zephyr-4-1
  self:
    path: config
